version: "3"
services:
  database:
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cake_db
      APP_DB_USER: postgres
      APP_DB_PASS: postgres
      APP_DB_NAME: cake_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql initdb.d/docker_postgres_init.sql
      - /var/lib/postgresql/data/
  api:
    build: packages/api
    ports:
      - "3001:3001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cake_db
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432